version: '3.8'

services:
  api:
    build: .
    container_name: api-emissao-de-faturas
    ports:
      - '3333:3333'
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start